import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, rm } from 'node:fs/promises';
import path from 'node:path';

const packagePath = process.env.PLAYWRIGHT_MODULE;
if (!packagePath) throw new Error('Set PLAYWRIGHT_MODULE to the installed Playwright package path.');
const require = createRequire(import.meta.url);
const { chromium } = require(packagePath);
const baseURL = process.env.SMOKE_URL || 'http://127.0.0.1:8765';
const localURL = process.env.SMOKE_LOCAL_URL;
const missingAdbURL = process.env.SMOKE_MISSING_ADB_URL;
const noauthURL = process.env.SMOKE_NOAUTH_URL;
const password = 'smoke6';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, acceptDownloads: true, colorScheme: 'dark' });
const pageErrors = [];
const watchRequests = [];
let monitoringRequests = 0;
let pairRequests = 0;
const finishRequests = [];
const deviceCreateRequests = [];
page.setDefaultTimeout(10000);
page.on('pageerror', error => pageErrors.push(error.message));
page.on('request', request => {
  if (request.method() === 'POST' && request.url().endsWith('/api/pair')) pairRequests += 1;
  if (request.method() === 'PUT' && request.url().endsWith('/api/monitoring')) monitoringRequests += 1;
  if (request.method() === 'POST' && /\/api\/devices\/[^/]+\/finish$/.test(new URL(request.url()).pathname)) finishRequests.push(request.postDataJSON());
  if (request.method() === 'POST' && request.url().endsWith('/api/devices')) deviceCreateRequests.push(request.postDataJSON());
  if (request.method() === 'POST' && /\/api\/devices\/[^/]+\/watch$/.test(new URL(request.url()).pathname)) watchRequests.push(request.postDataJSON());
});
const work = path.resolve('../../work');
const capture = name => page.screenshot({ path: path.join(work, name), fullPage: true });
const captureLocal = (target, name) => target.screenshot({ path: path.join(work, name), fullPage: true });
const wizardStep = number => page.locator(`.wizard-step[data-step="${number}"]`);
const status = async () => page.evaluate(async () => (await (await fetch('/api/status')).json()));

try {
  await mkdir(work, { recursive: true });
  assert.ok(localURL, 'smoke runner provides a separate local-setup fake server');
  assert.ok(missingAdbURL, 'smoke runner provides a separate missing-ADB fake server');
  assert.ok(noauthURL, 'smoke runner provides a login-disabled fake server');
  const localPage = await browser.newPage({ viewport: { width: 1280, height: 900 }, colorScheme: 'light' });
  let localSetupBody;
  localPage.on('request', request => {
    if (request.method() === 'POST' && request.url().endsWith('/api/setup')) localSetupBody = request.postDataJSON();
  });
  await localPage.goto(localURL);
  assert.equal(await localPage.locator('#bootstrap-help').isVisible(), false, 'bundled local setup hides token help in initial HTML');
  assert.equal(await localPage.locator('#token-label').isVisible(), false, 'bundled local setup hides token input in initial HTML');
  assert.equal(await localPage.locator('#token').isDisabled(), true);
  await localPage.locator('#appearance').selectOption('light');
  await captureLocal(localPage, 'local-account-light.png');
  await localPage.locator('#appearance').selectOption('night');
  await captureLocal(localPage, 'local-account-night.png');
  await localPage.locator('#password').fill(password);
  await localPage.locator('#auth-submit').click();
  await localPage.locator('#start-setup').waitFor();
  assert.deepEqual(Object.keys(localSetupBody).sort(), ['csrf', 'password'], 'password-only setup sends no token field');
  assert.equal(await localPage.evaluate(async () => (await (await fetch('/api/session')).json()).configured), true);
  await localPage.close();

  const missingAdbPage = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  await missingAdbPage.goto(missingAdbURL);
  await missingAdbPage.locator('#token').fill('fake-browser-smoke-bootstrap-token-2026-only');
  await missingAdbPage.locator('#password').fill(password);
  await missingAdbPage.locator('#auth-submit').click();
  await missingAdbPage.locator('#runtime-status').filter({hasText:'ADB is unavailable in this service runtime'}).waitFor();
  assert.match(await missingAdbPage.locator('#runtime-status').textContent(), /Source: (host|docker)\./, 'missing-ADB readiness warning identifies the configured runtime');
  await missingAdbPage.close();

  const noauthPage = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  let noauthCreateRequest;
  noauthPage.on('request', request => {
    if (request.method() === 'POST' && request.url().endsWith('/api/devices')) noauthCreateRequest={body:request.postDataJSON(),headers:request.headers()};
  });
  await noauthPage.goto(noauthURL);
  assert.equal(await noauthPage.locator('#auth-panel').isVisible(), false, 'login-disabled mode opens the dashboard without account setup');
  assert.equal(await noauthPage.locator('#dashboard').isVisible(), true);
  assert.equal(await noauthPage.locator('#logout').isVisible(), false, 'login-disabled mode hides sign out');
  const noauthSession=await noauthPage.evaluate(async () => (await (await fetch('/api/session')).json()));
  assert.equal(noauthSession.login_enabled, false);
  await noauthPage.evaluate(() => { document.cookie='tvcompiler_csrf=; Max-Age=0; path=/'; });
  assert.equal(await noauthPage.evaluate(() => document.cookie.includes('tvcompiler_csrf=')), false, 'noauth CSRF cookie can expire while the page remains open');
  await noauthPage.locator('#start-setup').click();
  await noauthPage.locator('#wizard-name').fill('No auth fixed TV');
  await noauthPage.locator('input[name="connection-mode"][value="tcpip"]').check();
  assert.equal(await noauthPage.locator('#wireless-pairing-options').isVisible(), false, 'fixed TCP/IP skips wireless pairing');
  await noauthPage.locator('#wizard-next').click();
  await noauthPage.locator('.wizard-step[data-step="2"]').waitFor({state:'visible'});
  assert.match(await noauthPage.locator('#wizard-connection-copy').textContent(), /unencrypted/i);
  assert.match(await noauthPage.locator('#wizard-connection-copy').textContent(), /RSA authorization prompt/i);
  assert.equal(await noauthPage.locator('#wizard-discover').isVisible(), false, 'fixed TCP/IP uses the configured endpoint without TLS discovery');
  await noauthPage.locator('#wizard-endpoint').fill('10.0.0.43:5555');
  await noauthPage.locator('#wizard-next').click();
  await noauthPage.locator('.wizard-step[data-step="3"]').waitFor({state:'visible'});
  assert.deepEqual(noauthCreateRequest?.body, {name:'No auth fixed TV',endpoint:'10.0.0.43:5555',connection_mode:'tcpip'});
  const noauthFreshSession=await noauthPage.evaluate(async () => (await (await fetch('/api/session')).json()));
  assert.notEqual(noauthFreshSession.csrf,noauthSession.csrf,'expired noauth CSRF cookie is replaced');
  assert.equal(noauthCreateRequest.headers['x-csrf-token'], noauthFreshSession.csrf, 'dashboard refreshes the no-login CSRF token before mutation');
  assert.equal(new URL(noauthCreateRequest.headers.referer).origin, new URL(noauthURL).origin, 'dashboard mutations retain same-origin protection');
  await noauthPage.locator('#wizard-app-skip').click();
  await noauthPage.locator('#wizard-next').click();
  await noauthPage.locator('.device').filter({hasText:'No auth fixed TV'}).waitFor();
  assert.match(await noauthPage.locator('.connection-method').textContent(), /Unencrypted fixed TCP\/IP/);
  await noauthPage.close();

  await page.goto(baseURL);
  const appearance = page.locator('#appearance');
  assert.equal(await appearance.inputValue(), 'system');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'system');
  assert.equal(await page.locator('html').evaluate(element => getComputedStyle(element).colorScheme), 'dark');
  await appearance.selectOption('light');
  assert.equal(await page.locator('html').evaluate(element => getComputedStyle(element).colorScheme), 'light');
  assert.equal(await page.locator('#bootstrap-help').isVisible(), true, 'setup help is visible before an account exists');
  assert.equal(await page.locator('#bootstrap-command').textContent(), 'cat /data/instance/bootstrap.token');
  await capture('account-setup-light.png');
  await appearance.selectOption('night');
  await capture('account-setup-night.png');
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async value => { window.__copiedCommand = value; } } }));
  await page.locator('#copy-bootstrap-command').click();
  await page.getByRole('status').filter({ hasText: 'Command copied.' }).waitFor();
  assert.equal(await page.evaluate(() => window.__copiedCommand), 'cat /data/instance/bootstrap.token', 'copy writes only the static retrieval command');
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('clipboard unavailable'); } } }));
  await page.locator('#copy-bootstrap-command').click();
  await page.getByRole('status').filter({ hasText: 'Could not copy automatically.' }).waitFor();
  assert.equal(await page.evaluate(() => window.getSelection().toString()), 'cat /data/instance/bootstrap.token', 'failed copy selects the static command for manual copying');
  assert.equal(await page.evaluate(() => Array.from({ length: localStorage.length }, (_, index) => localStorage.key(index)).some(value => value?.includes('fake-browser-smoke-bootstrap-token'))), false, 'bootstrap token is never persisted in browser storage');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'first-run help fits the mobile viewport');
  await page.reload();
  assert.equal(await page.locator('#appearance').inputValue(), 'night');
  assert.equal(await page.locator('html').evaluate(element => getComputedStyle(element).colorScheme), 'dark');

  await page.locator('#token').fill('fake-browser-smoke-bootstrap-token-2026-only');
  await page.locator('#password').fill(password);
  await page.locator('#auth-submit').click();
  await page.locator('#start-setup').waitFor();
  assert.equal(await page.locator('#bootstrap-help').isVisible(), false, 'setup help is hidden on the dashboard');
  assert.equal(await page.locator('#appearance').inputValue(), 'night');
  assert.equal(await page.locator('#advanced-settings').getAttribute('open'), null);
  assert.equal(await page.locator('#settings-form').isVisible(), false);
  assert.equal(await page.getByRole('button', { name: 'Start setup' }).count(), 1);
  await page.setViewportSize({ width: 1280, height: 900 });
  await capture('wizard-first-screen.png');
  assert.equal((await status()).monitoring_enabled, false);

  await page.locator('#logout').click();
  await page.locator('#auth-title').waitFor();
  assert.equal(await page.locator('#appearance').inputValue(), 'night');
  assert.equal(await page.locator('#auth-title').textContent(), 'Sign in');
  assert.equal(await page.locator('#bootstrap-help').isVisible(), false, 'setup help is hidden on sign-in');
  await page.locator('#password').fill(password);
  await page.locator('#auth-submit').click();
  await page.locator('#start-setup').waitFor();
  await page.locator('#appearance').selectOption('light');
  assert.equal(await page.locator('html').evaluate(element => getComputedStyle(element).colorScheme), 'light');
  await page.locator('#appearance').selectOption('system');
  assert.equal(await page.locator('html').evaluate(element => getComputedStyle(element).colorScheme), 'dark');

  await page.locator('#start-setup').click();
  assert.equal(await wizardStep(0).isVisible(), true);
  assert.equal(await wizardStep(1).isVisible(), false);
  await capture('wizard-name-step.png');
  await page.locator('#wizard-next').click();
  assert.equal(await page.locator('#wizard-name').evaluate(input => input.validity.valid), false);
  await page.locator('#wizard-name').fill('Smoke living room');
  await page.locator('#wizard-next').click();
  assert.equal(await wizardStep(1).isVisible(), true);
  assert.equal(await wizardStep(2).isVisible(), false);
  await page.locator('#wizard-next').click();
  assert.equal(await page.locator('#wizard-pair-endpoint').evaluate(input => input.validity.valid), false);
  await page.locator('#wizard-discover-pair').click();
  await page.getByText('pairing: 10.0.0.5:37123').waitFor();
  await page.getByRole('button', {name:'Use pairing endpoint'}).click();
  assert.equal(await page.locator('#wizard-pair-endpoint').inputValue(),'10.0.0.5:37123');
  await capture('wizard-pair-step.png');
  await page.locator('#wizard-pair-endpoint').fill('10.0.0.5:37123');
  await page.locator('#wizard-code').fill('123456');
  const submitWizardPair = page.locator('#wizard-next');
  await submitWizardPair.click();
  await page.waitForFunction(() => document.querySelector('#wizard-next').disabled);
  const pairingRun = await page.locator('#wizard').getAttribute('data-run');
  assert.equal(await page.locator('#setup-entry').isVisible(), false);
  assert.equal(await page.locator('#devices-section').isVisible(), false);
  assert.equal(await page.locator('#run-log').isVisible(), false);
  assert.equal(await page.locator('#advanced-settings').isVisible(), false);
  assert.equal(await page.locator('#dashboard-footer').isVisible(), false);
  assert.equal(await page.locator('#appearance').isVisible(), true);
  await page.locator('#start-setup').dispatchEvent('click');
  assert.equal(await page.locator('#wizard').getAttribute('data-run'), pairingRun, 'activation during pairing must not reset the run');
  await submitWizardPair.dispatchEvent('click');
  await wizardStep(3).waitFor({ state: 'visible' });
  assert.equal(pairRequests, 1, 'pair submission is protected against repeated clicks');
  assert.equal(await page.locator('#wizard-name').inputValue(), 'Smoke living room', 'reopening during pairing must preserve the active run');
  assert.equal(await page.locator('#wizard-code').inputValue(), '');
  assert.equal(await page.locator('#wizard-endpoint').inputValue(), '', 'automatic pairing success must not ask for the connection endpoint');
  assert.deepEqual(finishRequests, []);
  await page.locator('#wizard-apps .wizard-app').first().waitFor();
  await capture('wizard-app-step.png');
  const appChecks = page.locator('#wizard-apps input[type="checkbox"]');
  assert.equal(await appChecks.count(), 2);
  await appChecks.nth(0).check();
  const wizardSearch=page.locator('#wizard-apps input[type="search"]');
  await wizardSearch.fill('com.nuvio.tv.test');
  assert.equal(await appChecks.nth(0).isChecked(), true, 'filtering keeps hidden app selection');
  await appChecks.nth(1).check();
  await wizardSearch.fill('no-such-app');
  await page.getByRole('status').filter({hasText:'No apps match this search.'}).waitFor();
  await capture('wizard-search-step.png');
  assert.equal(await appChecks.nth(0).isChecked(), true);
  assert.equal(await appChecks.nth(1).isChecked(), true);
  await wizardSearch.fill('');
  await page.locator('#wizard-app-save').click();
  await page.waitForFunction(() => document.querySelector('#wizard-app-save').disabled);
  assert.equal(await appChecks.nth(0).isDisabled(), true, 'app selections lock while a save is pending');
  assert.equal(await page.locator('#wizard-app-skip').isDisabled(), true);
  assert.equal(await page.locator('#wizard-app-retry').isDisabled(), true);
  assert.equal(await appChecks.nth(0).isChecked(), true);
  assert.equal(await appChecks.nth(1).isChecked(), true);
  await page.locator('#wizard-app-save').dispatchEvent('click');
  await page.locator('#wizard-app-skip').dispatchEvent('click');
  await page.locator('#wizard-app-retry').dispatchEvent('click');
  await page.getByText(/Could not save com\.nuvio\.tv\.test/).waitFor();
  assert.equal(await appChecks.nth(0).isDisabled(), true);
  assert.equal(await appChecks.nth(1).isChecked(), true);
  const mainRequests = watchRequests.filter(request => request.package_id === 'com.nuvio.tv');
  const testRequests = watchRequests.filter(request => request.package_id === 'com.nuvio.tv.test');
  assert.equal(mainRequests.length, 1);
  assert.equal(mainRequests[0].initial_compile, false);
  assert.equal(testRequests.length, 1);
  assert.equal(testRequests[0].initial_compile, false);
  assert.deepEqual((await status()).jobs, [], 'guided baseline saves must not queue compiles');
  assert.equal((await status()).monitoring_enabled, false, 'setup must preserve paused monitoring');
  await page.locator('#wizard-app-save').click();
  await wizardStep(4).waitFor({ state: 'visible' });
  assert.equal(watchRequests.filter(request => request.package_id === 'com.nuvio.tv').length, 1, 'retry must not resave successful apps');
  assert.equal(watchRequests.filter(request => request.package_id === 'com.nuvio.tv.test').length, 2, 'retry only resaves the app whose response failed');
  await capture('wizard-review-step.png');
  assert.match(await page.locator('#wizard-review').textContent(), /Nuvio.*Nuvio Test/);
  assert.equal(await page.locator('#wizard-enable-monitoring').isChecked(), true, 'paused monitoring defaults to an explicit checked global enable');
  assert.equal(await page.locator('#wizard-queue-compiles').isChecked(), true, 'first compile queue choice defaults on');
  await page.locator('#wizard-enable-monitoring').uncheck();
  await page.locator('#wizard-queue-compiles').uncheck();
  await page.waitForTimeout(10200);
  assert.equal(await page.locator('#wizard-enable-monitoring').isChecked(), false, 'polling retains the monitoring choice');
  assert.equal(await page.locator('#wizard-queue-compiles').isChecked(), false, 'polling retains an explicit compile opt-out');
  assert.equal(await page.locator('#wizard-back').isVisible(), true);
  await page.locator('#wizard-back').click();
  await wizardStep(3).waitFor({ state: 'visible' });
  assert.equal(await page.locator('#wizard-back').isVisible(), false, 'a saved TV cannot navigate back into completed connection or pairing fields');
  assert.equal(await wizardStep(1).isVisible(), false);
  assert.equal(await wizardStep(2).isVisible(), false);
  await page.locator('#wizard-app-skip').click();
  await wizardStep(4).waitFor({ state: 'visible' });
  assert.equal(await page.locator('#wizard-enable-monitoring').isChecked(), false, 'Back preserves an explicit monitoring opt-out');
  assert.equal(await page.locator('#wizard-queue-compiles').isChecked(), false, 'Back preserves an explicit compile opt-out');
  const finishButton=page.locator('#wizard-next');
  let failFirstFinish=true;
  await page.route(/\/api\/devices\/[^/]+\/finish$/, async route => {
    if(failFirstFinish){failFirstFinish=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Injected one-time Finish failure.'})});return;}
    await route.continue();
  });
  await finishButton.click();
  await page.getByText(/Injected one-time Finish failure/).waitFor();
  assert.equal(await page.locator('#wizard-enable-monitoring').isChecked(), false, 'failed Finish preserves monitoring opt-out for retry');
  assert.equal(await page.locator('#wizard-queue-compiles').isChecked(), false, 'failed Finish preserves compile opt-out for retry');
  await finishButton.click();
  await page.unroute(/\/api\/devices\/[^/]+\/finish$/);
  await page.locator('.device').filter({ hasText: 'Smoke living room' }).waitFor();
  assert.equal((await status()).monitoring_enabled, false, 'Finish preserves the explicit monitoring opt-out');
  assert.deepEqual((await status()).jobs, []);
  assert.deepEqual(finishRequests.at(-1), {package_ids:[],queue_initial_compiles:false,enable_monitoring:false});
  assert.equal(finishRequests.length,2,'failed Finish is retried with its saved choices');
  const firstTv=page.locator('.device').filter({hasText:'Smoke living room'});
  const connectionCard=firstTv.locator('.connection-status');
  const connectionBadge=firstTv.locator('.connection-badge');
  await connectionCard.waitFor();
  assert.match(await connectionBadge.textContent(), /Connected|Offline|Authorization needed|Identity mismatch|ADB unavailable|Connection error|Status unknown/);
  assert.match(await connectionCard.textContent(), /Connected|Status not fresh|Status unknown/, 'TV card presents the backend connection state');
  assert.match(await connectionCard.textContent(), /Checked|Last checked|No connection check recorded/, 'TV card presents status freshness');
  assert.match(await connectionCard.textContent(), /Polling interval: \d+ seconds\./, 'TV card presents the polling interval even when monitoring is paused');
  assert.match(await page.locator('#runtime-status').textContent(), /ADB is available|ADB is unavailable/, 'dashboard shows runtime ADB readiness');

  // Pairing can succeed while endpoint lookup is unavailable; fallback adds without pairing again.
  const pairCountBeforeFallback=pairRequests;
  await page.getByRole('button', { name: 'Add another TV' }).click();
  await page.locator('#wizard-name').fill('Smoke fallback');
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-pair-endpoint').fill('10.0.0.11:37123');
  await page.locator('#wizard-code').fill('112233');
  await page.locator('#wizard-next').click();
  await wizardStep(2).waitFor({state:'visible'});
  assert.match(await page.locator('#wizard-error').textContent(), /Pairing succeeded/);
  assert.equal(await page.locator('#wizard-code').inputValue(), '');
  await page.locator('#wizard-back').click();
  assert.equal(await wizardStep(0).isVisible(), true, 'fallback can return to the TV name');
  await page.locator('#wizard-next').click();
  assert.equal(await wizardStep(2).isVisible(), true, 'continuing after fallback skips the consumed pairing step');
  assert.equal(await page.locator('#wizard-code').inputValue(), '');
  assert.equal(pairRequests,pairCountBeforeFallback+1,'back and continue does not repeat pairing');
  await capture('wizard-pair-fallback-connection.png');
  await page.locator('#wizard-endpoint').fill('10.0.0.11:41267');
  await page.locator('#wizard-next').click();
  await wizardStep(3).waitFor({state:'visible'});
  assert.equal(pairRequests,pairCountBeforeFallback+1);
  await page.locator('#wizard-app-skip').click();
  await page.locator('#wizard-next').click();
  await page.locator('.device').filter({hasText:'Smoke fallback'}).waitFor();
  assert.equal(pairRequests,pairCountBeforeFallback+1,'connection fallback does not repeat pairing');

  // Cancelled setup clears a transient code and reopening begins with clean fields.
  await page.getByRole('button', { name: 'Add another TV' }).click();
  await page.locator('#wizard-name').fill('Cancelled TV');
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-pair-endpoint').fill('10.0.0.8:37123');
  await page.locator('#wizard-code').fill('654321');
  await page.locator('#wizard-cancel').click();
  assert.equal(await page.locator('#wizard-code').inputValue(), '');
  await page.getByRole('button', { name: 'Add another TV' }).click();
  assert.equal(await page.locator('#wizard-code').inputValue(), '');
  assert.equal(await page.locator('#wizard-endpoint').inputValue(), '');
  await page.locator('#wizard-cancel').click();

  // A failed pairing exposes a manual retry without automatically replaying the mutation.
  const priorPairAttempts = pairRequests;
  await page.getByRole('button', { name: 'Add another TV' }).click();
  await page.locator('#wizard-name').fill('Smoke pair failure');
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-pair-endpoint').fill('10.0.0.10:37123');
  await page.locator('#wizard-code').fill('333333');
  await page.locator('#wizard-next').click();
  await page.getByText(/Injected one-time pairing failure/).waitFor();
  await page.waitForTimeout(900);
  assert.equal(pairRequests, priorPairAttempts + 1, 'failed pairing is not automatically retried');
  await page.locator('#wizard-cancel').click();

  // Pairing through this service's ADB keys skips the pairing code and /api/pair.
  const priorPairRequests = pairRequests;
  await page.getByRole('button', { name: 'Add another TV' }).click();
  await page.locator('#wizard-name').fill('Smoke bedroom');
  await page.locator('input[name="pairing-mode"][value="paired"]').check();
  await page.locator('#wizard-next').click();
  assert.equal(await wizardStep(2).isVisible(), true, 'already-paired TVs go directly to connection details');
  await page.locator('#wizard-endpoint').fill('10.0.0.6:41000');
  await page.locator('#wizard-next').click();
  await wizardStep(3).waitFor({ state: 'visible' });
  assert.equal(pairRequests, priorPairRequests);
  assert.equal(await page.locator('#wizard-code').inputValue(), '');
  await page.locator('#wizard-app-skip').click();
  assert.equal(await page.locator('#wizard-queue-compiles').isDisabled(), true, 'Finish cannot queue compiles when no app is selected');
  await page.locator('#wizard-next').click();
  await page.locator('.device').filter({ hasText: 'Smoke bedroom' }).waitFor();
  assert.equal((await status()).monitoring_enabled, true);

  // Existing device operations remain accessible but start collapsed.
  let card = page.locator('.device').filter({ hasText: 'Smoke bedroom' });
  assert.equal(await card.locator('.watched-summary').textContent(), 'No apps selected');
  const manageDetails = card.locator('details.device-manage');
  assert.equal(await manageDetails.getAttribute('open'), null);
  await manageDetails.locator('summary').click();
  await card.getByRole('textbox', { name: 'TV name' }).waitFor();
  await card.getByText(/Pinned TV serial:/).waitFor();
  const savedEndpoint=await card.getByRole('textbox',{name:'Connection IP:port for Smoke bedroom'}).inputValue();
  const savedSerial=(await card.getByText(/Pinned TV serial:/).textContent()).trim();
  const methodSelect=card.getByRole('combobox',{name:'Connection method'});
  assert.equal(await methodSelect.inputValue(),'wireless','new TVs default to Wireless debugging');
  await methodSelect.selectOption('tcpip');
  await card.getByRole('button',{name:'Save connection method'}).click();
  await page.getByText('Connection method choice saved. The TV endpoint and pinned identity were not changed.').waitFor();
  card=page.locator('.device').filter({hasText:'Smoke bedroom'});
  await card.locator('details.device-manage > summary').click();
  assert.equal(await card.getByRole('combobox',{name:'Connection method'}).inputValue(),'tcpip');
  assert.equal(await card.getByRole('textbox',{name:'Connection IP:port for Smoke bedroom'}).inputValue(),savedEndpoint);
  assert.equal((await card.getByText(/Pinned TV serial:/).textContent()).trim(),savedSerial);
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#start-setup').offsetParent!==null || document.querySelector('#auth-title').textContent==='Sign in');
  if(await page.locator('#auth-title').textContent()==='Sign in'){
    await page.locator('#password').fill(password);
    await page.locator('#auth-submit').click();
  }
  await page.locator('#start-setup').waitFor();
  card=page.locator('.device').filter({hasText:'Smoke bedroom'});
  await card.waitFor();
  await card.locator('details.device-manage > summary').click();
  assert.equal(await card.getByRole('combobox',{name:'Connection method'}).inputValue(),'tcpip','saved connection method survives a browser reload');
  assert.equal(await card.getByRole('textbox',{name:'Connection IP:port for Smoke bedroom'}).inputValue(),savedEndpoint,'mode edit does not change the saved endpoint');
  assert.equal((await card.getByText(/Pinned TV serial:/).textContent()).trim(),savedSerial,'mode edit does not change the pinned TV identity');
  await card.getByRole('combobox',{name:'Connection method'}).selectOption('wireless');
  await card.getByRole('button',{name:'Save connection method'}).click();
  await page.getByText('Connection method choice saved. The TV endpoint and pinned identity were not changed.').waitFor();
  card=page.locator('.device').filter({hasText:'Smoke bedroom'});
  await card.locator('details.device-manage > summary').click();
  assert.equal(await card.getByRole('combobox',{name:'Connection method'}).inputValue(),'wireless');
  const appsDetails = card.locator('details.app-management');
  assert.equal(await appsDetails.getAttribute('open'), null);
  await appsDetails.locator('summary').click();
  const loadApps = appsDetails.getByRole('button', { name: 'Load fresh app inventory' });
  assert.equal(await loadApps.isVisible(), true, 'fresh inventory action is available from app management');
  await loadApps.click();
  await card.getByText('com.nuvio.tv', { exact: true }).waitFor();
  const appSearch=appsDetails.locator('input[type="search"]');
  await appSearch.fill('no-such-app');
  await appsDetails.getByRole('status').filter({hasText:'No apps match this search.'}).waitFor();
  await appSearch.fill('nuvio');
  const mainAppRow=appsDetails.locator('.app-row[data-search="nuvio com.nuvio.tv"]');
  assert.equal(await mainAppRow.isVisible(), true, 'management search matches readable labels case-insensitively');
  await appSearch.fill('COM.NUVIO.TV');
  assert.equal(await mainAppRow.isVisible(), true, 'management search matches package IDs case-insensitively');
  await appSearch.fill('');
  const appRows = card.locator('.app-row');
  assert.equal(await appRows.count(), 2);
  const mainRow = appRows.nth(0);
  assert.equal(await mainRow.locator('code.package').textContent(), 'com.nuvio.tv');
  assert.equal(await mainRow.getByRole('checkbox').nth(1).isChecked(), false);
  assert.equal(await mainRow.getByRole('checkbox').nth(2).isChecked(), false);
  const watch = mainRow.getByRole('checkbox', { name: 'Watch Nuvio' });
  await watch.uncheck();
  await watch.check();
  await page.getByText(/Watching enabled\. Current version saved as its baseline/).waitFor();
  assert.match(await card.locator('.watched-summary').textContent(), /Watching: Nuvio/,
    'watching a previously-unwatched app updates the cached TV summary');
  await mainRow.getByRole('button', { name: 'Queue compile' }).click();
  await page.getByText('Manual compile queued. The scheduler will report its current wait reason.').waitFor();

  await page.locator('#advanced-settings > summary').click();
  const manualSetup=page.locator('#advanced-settings details').filter({hasText:'Manual TV setup'});
  await manualSetup.locator(':scope > summary').click();
  await manualSetup.locator('details').filter({hasText:'Add an already configured TV manually'}).locator('summary').click();
  const manualAdd=manualSetup.locator('#add-form');
  await manualAdd.locator('[name="name"]').fill('Smoke manual fixed');
  await manualAdd.locator('[name="connection_mode"]').selectOption('tcpip');
  await manualAdd.locator('[name="endpoint"]').fill('10.0.0.99:5555');
  await manualAdd.getByRole('button',{name:'Connect and add'}).click();
  await page.getByText('Added Smoke manual fixed after checking its TV identity.').waitFor();
  assert.deepEqual(deviceCreateRequests.at(-1),{name:'Smoke manual fixed',connection_mode:'tcpip',endpoint:'10.0.0.99:5555'},'manual add sends the chosen connection mode');
  await page.locator('.device').filter({hasText:'Smoke manual fixed'}).getByText(/Connection method: Unencrypted fixed TCP\/IP/).waitFor();
  await page.locator('#advanced-settings details').filter({ hasText: 'Global scheduling' }).locator('summary').click();
  await page.locator('#settings-form [name="poll_interval_seconds"]').fill('120');
  await page.locator('#settings-form [name="max_attempts"]').fill('4');
  await page.locator('#settings-form [name="window_start"]').fill('23:00');
  await page.locator('#settings-form [name="window_end"]').fill('06:00');
  assert.equal(await page.locator('#settings-form [name="timezone"] option[value="America/Chicago"]').textContent(), 'Chicago (America/Chicago)');
  await page.locator('#settings-form [name="timezone"]').selectOption('America/Chicago');
  await page.locator('#settings-form button[type="submit"]').click();
  await page.getByText('Global scheduling settings saved.').waitFor();
  assert.equal(await page.locator('#settings-form [name="timezone"]').inputValue(), 'America/Chicago', 'status refresh keeps the saved time-zone choice');
  await page.locator('#advanced-settings details').filter({ hasText: 'Monitoring control' }).locator('summary').click();
  await page.locator('#monitor-toggle').click();
  await page.getByText('Monitoring is paused. Setup and app selection do not change this setting.').waitFor();
  assert.equal((await status()).monitoring_enabled, false);
  await page.locator('#monitor-toggle').click();
  await page.getByText('Monitoring is on. Automatic checks follow the saved schedule.').waitFor();
  assert.equal((await status()).monitoring_enabled, true);
  const monitoringBeforeWizardResume = monitoringRequests;
  await page.getByRole('button', { name: 'Add another TV' }).click();
  await page.locator('#wizard-name').fill('Smoke active');
  await page.locator('input[name="pairing-mode"][value="paired"]').check();
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-endpoint').fill('10.0.0.7:41000');
  await page.locator('#wizard-next').click();
  await wizardStep(3).waitFor({ state: 'visible' });
  await page.locator('#wizard-apps input[type="checkbox"]').first().check();
  await page.locator('#wizard-app-save').click();
  await wizardStep(4).waitFor({ state: 'visible' });
  assert.equal(await page.locator('#wizard-enable-monitoring').isChecked(), true);
  assert.equal(await page.locator('#wizard-enable-monitoring').isDisabled(), true, 'Finish cannot pause monitoring that is already enabled');
  assert.equal(await page.locator('#wizard-queue-compiles').isChecked(), true, 'first compile queue choice defaults on for a later setup');
  assert.equal((await status()).monitoring_enabled, true);
  await page.locator('#wizard-next').click();
  assert.equal((await status()).monitoring_enabled, true, 'Finish preserves the active monitoring setting');
  assert.equal(monitoringRequests, monitoringBeforeWizardResume, 'Finish preserves active monitoring without a separate partial update');
  const queuedFinish=finishRequests.at(-1);
  assert.deepEqual(queuedFinish.package_ids,['com.nuvio.tv']);
  assert.equal(queuedFinish.queue_initial_compiles,true);
  assert.equal(queuedFinish.enable_monitoring,false);
  const queuedJob=(await status()).jobs.find(job=>job.package_id==='com.nuvio.tv');
  assert.ok(queuedJob,'explicit Finish consent creates a job');
  assert.equal(queuedJob.manual,true);
  assert.equal(queuedJob.state,'pending','active playback defers the explicitly queued job');
  const [download] = await Promise.all([page.waitForEvent('download'),page.locator('#diagnostics').click()]);
  assert.match(download.suggestedFilename(), /diagnostics\.json$/);

  // A delayed inventory response must not write into a new signed-out session.
  await page.getByRole('button', { name: 'Add another TV' }).click();
  await page.locator('#wizard-name').fill('Smoke stale');
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-pair-endpoint').fill('10.0.0.9:37123');
  await page.locator('#wizard-code').fill('222222');
  await page.locator('#wizard-next').click();
  await page.getByText('Loading installed apps…').waitFor();
  await page.locator('#logout').click();
  await page.getByRole('heading', { name: 'Sign in' }).waitFor();
  await page.waitForTimeout(950);
  assert.equal(await page.locator('#auth-title').textContent(), 'Sign in', 'stale inventory must not replace the signed-out view');
  await page.locator('#password').fill(password);
  await page.locator('#auth-submit').click();
  await page.locator('.device').filter({ hasText: 'Smoke stale' }).waitFor();
  assert.equal(await page.locator('#wizard').isVisible(), false);

  await page.setViewportSize({ width: 1280, height: 900 });
  await page.locator('#appearance').selectOption('light');
  await capture('dashboard-light-desktop.png');
  await page.locator('#appearance').selectOption('night');
  await capture('dashboard-night-desktop.png');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#appearance').selectOption('light');
  await capture('dashboard-light-mobile.png');
  await page.locator('#appearance').selectOption('night');
  await capture('dashboard-night-mobile.png');
  await page.getByRole('button', { name: 'Add another TV' }).click();
  assert.equal(await wizardStep(0).isVisible(), true);
  assert.equal(await page.locator('#wizard-code').inputValue(), '');
  assert.equal(await page.locator('#devices-section').isVisible(), false);
  await page.setViewportSize({ width: 1280, height: 900 });
  await capture('wizard-night-desktop.png');
  const contrast = await page.evaluate(() => {
    const channels = color => color.match(/[\d.]+/g)?.slice(0, 3).map(Number);
    const luminance = color => {
      const values=channels(color).map(value=>{const c=value/255;return c<=0.04045?c/12.92:((c+0.055)/1.055)**2.4;});
      return values[0]*0.2126+values[1]*0.7152+values[2]*0.0722;
    };
    const ratio = (foreground,background) => {const a=luminance(foreground),b=luminance(background);return (Math.max(a,b)+0.05)/(Math.min(a,b)+0.05);};
    const background = element => {
      for(let node=element;node;node=node.parentElement){const value=getComputedStyle(node).backgroundColor;if(!value.includes('0, 0, 0, 0')&&!value.includes('rgba(0, 0, 0, 0)'))return value;}
      return getComputedStyle(document.body).backgroundColor;
    };
    const muted=document.querySelector('#wizard .muted');
    const placeholder=document.querySelector('#wizard-name');
    return {
      body:ratio(getComputedStyle(document.body).color,background(document.body)),
      muted:ratio(getComputedStyle(muted).color,background(muted)),
      placeholder:ratio(getComputedStyle(placeholder,'::placeholder').color,background(placeholder)),
    };
  });
  for (const [surface, value] of Object.entries(contrast)) assert.ok(value >= 4.5, `${surface} contrast must meet 4.5:1, got ${value.toFixed(2)}:1`);
  await page.locator('#appearance').selectOption('light');
  await page.setViewportSize({ width: 390, height: 844 });
  await capture('wizard-light-mobile.png');
  await page.locator('#wizard-cancel').click();
  await page.setViewportSize({ width: 360, height: 800 });
  const overflow = await page.evaluate(() => ({
    width: document.documentElement.scrollWidth,
    viewport: window.innerWidth,
    offenders: Array.from(document.querySelectorAll('body *')).map(element => ({tag:element.tagName,id:element.id,className:typeof element.className==='string'?element.className:'',right:Math.round(element.getBoundingClientRect().right),text:(element.textContent||'').trim().slice(0,70)})).filter(item=>item.right>window.innerWidth+1).slice(0,8),
  }));
  assert.equal(overflow.width>overflow.viewport, false, `mobile layout should not overflow horizontally: ${JSON.stringify(overflow)}`);

  const blockedStoragePage = await browser.newPage({ colorScheme: 'dark' });
  blockedStoragePage.on('pageerror', error => pageErrors.push(error.message));
  await blockedStoragePage.addInitScript(() => Object.defineProperty(window, 'localStorage', {
    configurable: true,
    get() { throw new Error('Storage is disabled.'); },
  }));
  await blockedStoragePage.goto(baseURL);
  assert.equal(await blockedStoragePage.locator('#appearance').inputValue(), 'system');
  await blockedStoragePage.locator('#appearance').selectOption('light');
  assert.equal(await blockedStoragePage.locator('html').evaluate(element => getComputedStyle(element).colorScheme), 'light');
  await blockedStoragePage.close();

  assert.deepEqual(pageErrors, [], 'browser must not report JavaScript errors');
  console.log('browser smoke passed: password-only local account setup, token-required setup with static command copy success/failure, missing-ADB warning, token storage exclusion, login/dashboard help visibility, wizard pairing branches, endpoint selection, validation, code clearing, duplicate protection, partial-save retry, checked Finish defaults and saved opt-outs across polling/Back/retry, per-TV status cards, app search, timezone selection, TV/app management, settings/diagnostics, Appearance, mobile overflow; screenshots saved under ../../work');
} catch (error) {
  for (const filename of ['account-setup-light.png','account-setup-night.png','wizard-first-screen.png','wizard-name-step.png','wizard-connection-step.png','wizard-pair-step.png','wizard-app-step.png','wizard-review-step.png','wizard-night-desktop.png','dashboard-light-desktop.png','dashboard-night-desktop.png','dashboard-light-mobile.png','dashboard-night-mobile.png','wizard-light-mobile.png']) await rm(path.join(work, filename), { force: true });
  throw error;
} finally {
  await browser.close();
}
